### 데이터 받아오기

In [3]:
import json
import numpy as np
import random
import nltk

In [4]:
with open("reviews_Books_5.json","r") as data_file:
    raw_data=data_file.readlines()

In [5]:
json_list = []
for i in range(len(raw_data)):
    try:
        json_data = json.loads(raw_data[i])
        json_list.append(json_data)
    except:
        print(raw_data[i],i)

{"reviewerID": "AAXUNK0W2DZG5", "asin": "0060520841", "reviewerName": "Amazon Customer \"leneker\"", "helpful": [5, 10], "reviewText": "1996 Bernard Goldberg wrote an editorial for the Wall Street Journal that said there was an obvious bias on the part of network new shows  for the liberal point of view.  he then illustrated this with an example that he dissected in-depth.  The reaction to this observation was the ruination of her career, and the beginning of his status as a pariah among most newsmen.  This book is used to add more ammo to the controversy.That the journalists who so eagerly pry into other peoples lives and business should be reluctant to be examined is hardly surprising.  Almost no one really wants to have his life or business dissected by Mike Wallace not even Dan Rather.  Some facts in this book are really potent such as the survey results which show how the average journalist and the average American are often vastly at odds.  Other chapters highlight different stor

### 데이터 분리하기

In [6]:
review_data = []

for i in range(len(json_list)):
    review_dict={}
    review_dict["reviewText"] = json_list[i]["reviewText"]
    review_dict["overall"] = json_list[i]["overall"]
    review_data.append(review_dict)

In [7]:
reviewText = []
for i in range(len(review_data)):
    reviewText.append(review_data[i]["reviewText"])

In [8]:
reviewText[9]

"An amazing work. Realizing extensive use of Biblical imagery and sentence structure, &#34;The Prophet&#34; by Khalil Gibran is a literary classic. Influencing the Free Love movement of the 1960's, Gibran's master work explores themes of love, longing and loss."

In [9]:
y_data = []
for i in range(len(review_data)):
    y_data.append(review_data[i]["overall"])

In [10]:
from collections import Counter
Counter(y_data)

Counter({1.0: 4239, 2.0: 5102, 3.0: 10177, 4.0: 21555, 5.0: 52111})

<h3>데이터 전처리</h3>

In [11]:
from nltk.corpus import stopwords
from bs4 import BeautifulSoup
import re

In [12]:
def review_to_words(raw_review):
    # Function to convert a raw review to a string of words
    # The input is a single string (a raw movie review), and 
    # the output is a single string (a preprocessed movie review)
    
   
    cleaned_text_list=[]
    for i in range(len(raw_review)):
        
        review_text = BeautifulSoup(raw_review[i]).get_text()
        letters_only = re.sub("[^a-zA-Z]", " ", review_text)
        words = letters_only.lower().split()
        cleaned_text = " ".join(words)
        cleaned_text_list.append(cleaned_text)

    return cleaned_text_list

       

In [13]:
pre_data=review_to_words(reviewText)

c:\users\jangy\miniconda3\envs\bi_project\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file c:\users\jangy\miniconda3\envs\bi_project\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "html5lib")

  markup_type=markup_type))


In [14]:
len(pre_data)

93184

### 데이터 셔플

In [15]:
c = list(zip(pre_data, y_data))
random.shuffle(c)

In [16]:
a, b = zip(*c)

In [17]:
pre_text=list(a)
overall=np.array(list(b))

In [28]:
pre_text

['very entertaining i continue to enjoy the character development today i even had a discussion with somebody about what faction i would be two thumbs up',
 'water for elephants is an unusual story that i found captivating and difficult to put down the story is well written and provides a glimpse into circus life and the cruel times during the early years in the twentieth century i would recommend it to anyone looking for a fast paced story that is a wee bit like grapes of wrath but less dark',
 'as a college student studying international affairs i managed to avoid the israeli palestinian conflict for years i never felt like i had a fight in it and felt the field had too many cooks in the kitchen i focused mostly on other regions and topics generally aware of big picture issues with israel settlements and the plight of palestinians i came across this book in searching for books on syrian history for my job and decided to give it a shot at least for the portions covering lebanese histo

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(analyzer='word', sublinear_tf=True,lowercase=True)
vectorizer = TfidfVectorizer(ngram_range=(1,2))

tfidf = vectorizer.fit_transform(pre_text)

In [27]:
print(tfidf)

  (0, 2519843)	0.0542605994112
  (0, 734934)	0.10121087131
  (0, 507258)	0.115167202474
  (0, 2390383)	0.0275766273453
  (0, 728289)	0.0849564437069
  (0, 2294640)	0.0250251347342
  (0, 412521)	0.0734367423422
  (0, 612519)	0.108681126233
  (0, 2405750)	0.100346590463
  (0, 755078)	0.0614855586069
  (0, 997588)	0.0577411191784
  (0, 636983)	0.127697497316
  (0, 2625879)	0.0387244391771
  (0, 2136124)	0.155801905308
  (0, 2851)	0.0482518864716
  (0, 2583769)	0.0511275484412
  (0, 797498)	0.153891979934
  (0, 2660168)	0.0559727503875
  (0, 234252)	0.044976583902
  (0, 2457214)	0.06918487156
  (0, 2379100)	0.177562860359
  (0, 2493141)	0.055890226422
  (0, 2520613)	0.149028640918
  (0, 735039)	0.268189571247
  (0, 507426)	0.132240385863
  :	:
  (93183, 998896)	0.134654872658
  (93183, 1183647)	0.12413042199
  (93183, 840835)	0.134654872658
  (93183, 1782299)	0.144916311418
  (93183, 2355999)	0.127699679799
  (93183, 1885752)	0.131502679176
  (93183, 106887)	0.127699679799
  (93183, 203318

### 가장 작은 평점으로 갯수 맞추기

In [17]:
from collections import Counter
length=sorted(Counter(overall).most_common())[0][1]

In [18]:
search=[1.0,2.0,3.0,4.0,5.0]
count=0
text=[]
y=[]

for i in search:
    count=0
    for index,value in enumerate(overall):
        if (count==length): break
        elif (i==value):
            text.append(pre_text[index])
            y.append(value)
            count=count+1

In [19]:
Counter(y)

Counter({1.0: 323833, 2.0: 323833, 3.0: 323833, 4.0: 323833, 5.0: 323833})

In [20]:
print(len(text), len(y))

1619165 1619165


<h3>데이터 셔플 다시</h3>

In [21]:
c = list(zip(text, y))
random.shuffle(c)

In [22]:
a, b = zip(*c)

In [23]:
text_data=list(a)
overall_data=np.array(list(b))

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(analyzer='word', sublinear_tf=True,lowercase=True)
vectorizer = TfidfVectorizer(ngram_range=(1,2))

tfidf = vectorizer.fit_transform(text_data)

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(tfidf , overall_data , test_size=0.33, random_state=100)

In [26]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((1084840, 20596668), (1084840,), (534325, 20596668), (534325,))

### 예측

#### Multiclass SVM

In [27]:
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC

result = OneVsRestClassifier(LinearSVC(random_state=100)).fit(x_train, y_train)
result = result.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(result ,y_test)

0.55077153417863656

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_test, result))

             precision    recall  f1-score   support

        1.0       0.63      0.69      0.66    106659
        2.0       0.48      0.44      0.46    107247
        3.0       0.50      0.46      0.48    106991
        4.0       0.49      0.47      0.48    106970
        5.0       0.63      0.70      0.66    106458

avg / total       0.54      0.55      0.55    534325



### LogisticRegression

In [30]:
from sklearn import linear_model
logreg = linear_model.LogisticRegression()

logreg.fit(x_train, y_train)
logreg.predict(x_test)==y_test

array([ True,  True, False, ...,  True, False, False], dtype=bool)

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(logreg.predict(x_test), y_test)

0.58050250315819019

In [32]:
from sklearn.metrics import precision_score
precision_score(logreg.predict(x_test), y_test,average=None) 

array([ 0.71789535,  0.46698742,  0.49167687,  0.49688698,  0.73049466])

In [33]:
from sklearn import metrics
fpr_1, tpr_1, thresholds = metrics.roc_curve(y_test, logreg.predict(x_test), pos_label=1)
metrics.auc(fpr_1, tpr_1)

0.11702783317605014

In [34]:
fpr_2, tpr_2, thresholds = metrics.roc_curve(y_test, logreg.predict(x_test), pos_label=2)
metrics.auc(fpr_2, tpr_2)

0.2684977087352195

In [44]:
fpr_3, tpr_3, thresholds = metrics.roc_curve(y_test, logreg.predict(x_test), pos_label=3) ######여기다시
metrics.auc(fpr_3, tpr_3)

0.49178580122519733

In [36]:
fpr_4, tpr_4, thresholds = metrics.roc_curve(y_test, logreg.predict(x_test), pos_label=4)
metrics.auc(fpr_4, tpr_4)

0.73553431905837741

In [37]:
fpr_5, tpr_5, thresholds = metrics.roc_curve(y_test, logreg.predict(x_test), pos_label=5)
metrics.auc(fpr_5, tpr_5)

0.88816411987429345

In [38]:
print(y_test[:20], logreg.predict(x_test)[:20])

[ 1.  1.  4.  1.  1.  2.  4.  3.  1.  2.  3.  5.  1.  2.  4.  2.  4.  1.
  1.  4.] [ 1.  1.  5.  1.  1.  2.  4.  3.  1.  2.  3.  5.  2.  2.  5.  1.  5.  1.
  2.  4.]


In [39]:
logreg.predict(x_test)[:10]

array([ 1.,  1.,  5.,  1.,  1.,  2.,  4.,  3.,  1.,  2.])

In [40]:
result=logreg.predict(x_test)

In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_test, result))

             precision    recall  f1-score   support

        1.0       0.64      0.72      0.68    106659
        2.0       0.52      0.47      0.49    107247
        3.0       0.54      0.49      0.51    106991
        4.0       0.53      0.50      0.51    106970
        5.0       0.65      0.73      0.69    106458

avg / total       0.57      0.58      0.58    534325



### INPUT 

In [42]:
texts = ["""I enjoyed this book, as long as I kept in mind that the book was written for young adults.  
         The characters were believable and it was easy to identify with their pain.""",
        "I think the author gets lost in his own thoughts and trys to make storys of something that's not there.",
        """I was very excited to start reading this book and although I did like it, 
        I thought that a lot of the words to describe body parts was kind of high-schoolish.  
        Didn't care for the cliff hanging ending.""",
        """I don't know if you are familiar with FANFIC on the internet but that what this book reminded me of.  
        I love the series and thought I would like the books...not so much.""",
        """As I love western era romances, this one was wonderful.  An easy read and ended the way we always hope....happily!"""]
overall=[4,1,3,2,5]
vecs = vectorizer.transform(texts) 

In [43]:
print(overall,logreg.predict(vecs))

[4, 1, 3, 2, 5] [ 4.  1.  3.  3.  5.]
